### PR TITLE
Fix/issue161/mobile display of alerts player

### LINKED ISSUE #161: Mobile display issue, image area does not adapt to screen size
There is a display issue on mobile devices where the image area does not properly adapt to the screen size. As shown in the example image below

Image

### PR DESCRIPTION
**Pull request by Yoctoboy**
## Issue
Fixes #161 

## Loom
https://www.loom.com/share/e49931d29dc8449792eee1bdebdc4c89

## Screens
Before:
image

After:
image

### CODE REVIEW

File: src/components/Common/SplitButton.tsx [hunk 1]
```diff
@@ -74,6 +74,7 @@ export const SplitButton = ({
           aria-label={options[0].label}
           aria-haspopup="menu"
           onClick={handleToggle}
+          sx={{ px: 0 }}
```
Comment (Yoctoboy) [inline src/components/Common/SplitButton.tsx]: this reduces padding around the download sub-button (ArrowDropDownIcon).

Before:

Image

After:

Image
